services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "<REDACTED>"
        NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: "/profile"
    working_dir: /app
    ports:
      - "3000:3000"
    image: unischeduler-app
    env_file:
      - .env
    depends_on:
      - database
      - scheduler

  database:
    image: 'postgres:latest'
    ports:
      - 15432:5432
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data/

  scheduler:
    image: 'stmagalios/university-scheduler-server:latest'
    ports:
      - 18080:8080

volumes:
  database-data:    
