services:
  database:
    image: 'postgres:latest'
    ports:
      - 15432:5432
    env_file:
      - .env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  scheduler:
    image: 'stmagalios/university-scheduler-server:latest'
    ports:
      - 18080:8080
    
