import { type GetServerSideProps } from "next";
import { signIn } from "next-auth/react";
import Head from "next/head";
import { getServerAuthSession } from "~/server/auth";

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const session = await getServerAuthSession(ctx);

  if (session !== null) {
    return {
      redirect: {
        destination: "/profile",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
};

export default function Home() {
  function handleLogin() {
    void signIn("google");
  }

  return (
    <>
      <Head>
        <title>UniScheduler</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col justify-center gap-24">
        {/* Title */}
        <div className="flex flex-col items-center">
          <h1 className="text-9xl font-bold">UniScheduler</h1>
          <p className="text-3xl text-gray-400">
            The university timetable creator
          </p>
        </div>

        {/* Login */}
        <div className="flex justify-center">
          <button
            onClick={handleLogin}
            className="cursor-not-allowed rounded-lg bg-red-600 px-4 py-3 disabled:bg-red-400"
          >
            Login with <span className="font-semibold">Google Account</span>
          </button>
        </div>
      </main>
    </>
  );
}
