import Head from "next/head";

export default function Profile() {
  return (
    <>
      <Head>
        <title>Profile | UniScheduler</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      profile page
    </>
  );
}
