import { type GetServerSideProps } from "next";
import { signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { getServerAuthSession } from "~/server/auth";

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const session = await getServerAuthSession(ctx);

  if (session === null) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
};

export default function Profile() {
  const { status, data: session } = useSession();

  return (
    <>
      <Head>
        <title>Profile | UniScheduler</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>profile page</p>
      <p>Status: {status}</p>
      <pre>
        <p>data: {JSON.stringify(session, null, 2)}</p>
      </pre>

      <button onClick={() => void signOut()} className="bg-green-500">
        Sign out
      </button>
    </>
  );
}
